#!/bin/bash

# Expects name of input file in first command line argument
file=$1

# Extract list of standard names from xml file and remove entry id xml tags
# Output file is called 'output.txt' in current working directory
grep "entry id" $file | sed -e 's/   <entry id="//' -e 's/">//' > output.txt

# Insert standardname([' at the start of every line
sed -i "s/^/standardname(['/" output.txt

# Insert ']). at end of every line
sed -i "s/$/'])./" output.txt

# Replace underscores with commas
sed -i "s/_/','/g" output.txt

