title: CF Conventions
description: CF Conventions
url: http://cfconventions.org/
repository: cf-convention/cf-convention.github.io

markdown: kramdown

exclude:
  - ".gitignore"
  - CNAME
  - Gemfile
  - README.md
  - CONTRIBUTING.md
  # Should be removed from repo ?? Some converted to GitHub Actions?
  - Data/docbook-xsl-1.73.2
  - Data/area-type-table/*/get-title-version.py
  - Data/area-type-table/*/makefile
  - Data/area-type-table/*/README.txt
  - Data/area-type-table/*/xsl/
  - Data/cf-conventions/cf-conventions-*/encode.py
  - Data/cf-conventions/cf-conventions-*/makefile
  - Data/cf-conventions/cf-conventions-*/README.txt
  - Data/cf-conventions/cf-conventions-*/docbooksrc/
  - Data/cf-conventions/cf-conventions-*/xsl/
  - Data/cf-standard-names/*/inject-area-type-link.py
  - Data/cf-standard-names/*/kwic_edit
  - Data/cf-standard-names/*/makefile
  - Data/cf-standard-names/*/README.txt
  - Data/cf-standard-names/*/xsl/