#!/bin/bash

dir=/home/a001257/CODE/cf-conventions/cf-convention.github.io/Data/cf-standard-names
for d in $(seq 1 84); do 
    if [[ "$d" != "38" ]]; then
        f=$(ls $dir/$d/src/*__SAVED.xml)
        mv $f ${f/__SAVED/}
        # rm $dir/$d/src/*
    fi
done
